# -*- coding: utf-8 -*-
"""206_VACM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-RcLBHTgEZEBfI2bzfsCEqAVkOVqI8nv
"""

#operacion con lista
#melina vargas

frutas = ['manzana' , 'pera' , 'uva' , 'mango']

print(frutas[0]) # mostrar la primera fruta
print(frutas[-1]) #mostrar la ultima fruta

frutas[1] = 'naranja' #notificacion e posicion 1
frutas.append('kiwi') #agregar al final
frutas.insert(1, 'fresa')

#lista con numeros
#vargas melina

numeros = [45, 12, 17, 78, 3, 56, 89, 23, 67, 1, 34]
print('original:' , numeros)

#ordenar de mayor a menor
numeros. sort()
print('ordenar:', numeros)

#ordenar de mayor a menor
numeros.reverse()
print('invertida:' , numeros)

total = sum(numeros)
numeros = [45,12,17,78,3,56,89,23,67,1,34]
promedio = sum(numeros) / len(numeros)
print(f'suma: {total}')
print(f'promedio: {promedio:.2f}')